### ISSUE TITLE
Installation gives AttributeError: 'NoneType' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by mback2k** [jhemp/intelmq-tools#3]
After applying the workarounds given in #1 and #2, trying to install a custom bot unfortunately still gives the following error with IntelMQ version 2.3.3:

```
Traceback (most recent call last):
  File "/opt/intelmq-tools/intelmq_tools.py", line 40, in <module>
    main()
  File "/opt/intelmq-tools/intelmq_tools.py", line 34, in main
    sys.exit(tools.run())
  File "/opt/intelmq-tools/intelmqtools/intelmqtool.py", line 207, in run
    return self.run_tool(key, args)
  File "/opt/intelmq-tools/intelmqtools/intelmqtool.py", line 97, in run_tool
    return instance.start(args)
  File "/opt/intelmq-tools/intelmqtools/tools/installer.py", line 64, in start
    self.manipulate_bots_file(bot, True)
  File "/opt/intelmq-tools/intelmqtools/tools/installer.py", line 49, in manipulate_bots_file
    self.update_bots_file(installed_bots, 'insert')
  File "/opt/intelmq-tools/intelmqtools/tools/abstractbasetool.py", line 607, in update_bots_file
    running_bots[bot.bot_type][bot.bots_config.name] = bot.bots_config.to_dict(bot.module)
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

**Comment by jhemp** [comment]
Closed as #1 and #2 have been fixed due to redesings
